### PR TITLE
Quick fix to place logo and content over ribbon

### PR DESCRIPTION
**Pull request by codejet**

### CODE REVIEW

**Comment by jwoschitz** [comment]
This fix works pretty well but unfortunately it looks really weird if the logo is in front of the ribbon:

https://imgur.com/AmvKh

**Comment by codejet** [comment]
I think it also looks weird if it's behind the ribbon... :)

**Comment by jwoschitz** [comment]
yeah, that's true. I added a media screen hack 037d7a9 to hide the ribbon on smaller resolutions, seems to work so far.

**Comment by codejet** [comment]
there are several possible ways to tackle this, but pull request comments are probably not the best way to discuss this ;)

**Pull request merged**
